### TTS

In [1]:
import pandas as pd

data = pd.read_csv("./output/output(LE).csv")

In [2]:
data

,MESURE_AGE_CO,SEXDSTN_FLAG_CD,MESURE_IEM_001_VALUE,MESURE_IEM_002_VALUE,MESURE_IEM_003_VALUE,MESURE_IEM_005_VALUE,MESURE_IEM_006_VALUE,start,main,end
0,64,1,166.6,79.3,36.3,85.0,147.0,[517],[378 652 77 476 92 96 66 625 621 135 119 ...,[507]
1,60,1,174.2,74.1,26.8,94.0,148.0,[477],[199 625 661 378 652 299 65 424 621 476 77],[639 640 285]
2,65,1,163.4,59.0,21.1,74.0,152.0,[507 477],[378 207 608 203 205 309],[517]
3,35,1,178.2,85.3,24.1,90.0,141.0,[512 477 585],[611 329 119 313],[639 417 285 172 517]
4,75,1,168.0,62.6,20.4,76.0,136.0,[613 446 8 450 634 633],[517 477 541 585],[130]
...,...,...,...,...,...,...,...,...,...,...
747727,15,2,163.1,85.1,45.5,89.0,139.0,[517],[611 329 424 449 632 246],[507]
747728,14,1,183.3,62.3,13.5,71.0,130.0,[477],[157 470 514 520 473 378 387 217 163 536 662],[531]
747729,15,1,180.3,71.9,21.1,62.0,100.0,[ 93 51 172 8 477],[157 470 514 520 473 378 387 217 163 536 662],[531]
747730,15,2,155.0,58.0,33.5,82.0,145.0,[477],[157 470 514 520 473 378 387 217 163 536 662],[531]
747731,14,1,176.0,54.7,9.9,60.0,109.0,[477],[157 470 514 520 473 378 387 217 163 536 662],[531]

In [2]:
import numpy as np
data['start'] = data['start'].apply(lambda x: [int(i) for i in x.strip('[]').split()])
data['main'] = data['main'].apply(lambda x: [int(i) for i in x.strip('[]').split()])
data['end'] = data['end'].apply(lambda x: [int(i) for i in x.strip('[]').split()])

ValueError: invalid literal for int() with base 10: '513,'

In [4]:
data.to_csv('output/output(LE).csv', index=False)